### ISSUE TITLE
[FEATURE] Provide a way to force stop sounds

### ISSUE THREAD

**Issue by aburkowsky9** [twilio/twilio-voice.js#222] opened 2023-11-30 16:21 UTC
**Is your feature request related to a problem? Please describe.**
For various reasons there are instances of the device continuing to play sounds like the `Incoming` ringing sound after answering, ending, or rejecting a call. The only remedy I am currently aware of outside of a larger refactor is to access the private property `_soundcache` on the `Device` and stop the sound using something like the following:
```ts
  const stopIncomingCallSound = useCallback(() => {
    const soundCache: Map<Device.SoundName, { stop: () => void }> | undefined =  state.device?._soundcache;
    soundCache?.get(Device.SoundName.Incoming)?.stop();
  }, [state.device]);
```

**Describe the solution you'd like**
This is clearly undesirable since the `_soundcache` property is private and should be inaccessible. Im sure direct access is not a stable feature. It would be much better to have an exposed method on the `Device` or `Call` instance to force change in `play` state of a sound. 

**Describe alternatives you've considered**
Clearly there are other issues causing this kind of behavior. Largely there are some architectural concerns that will take time to implement on our side, but there is also the possibility of an existing bug in the SDK itself, but this seems like a reasonable feature to provide as an escape hatch.

```ts
device?.audio?.incoming(false);
```
While the method on the `audio` property is available to disable sounds is available this method doesn't seem to work with my specific case and it's also problematic in that I would have to reenable the sound at some point.

**Additional context**
None

**Comment by charliesantos** [comment] 2023-11-30 16:46
@aburkowsky9 thanks for reaching out. We will consider this feature request.
Regarding the issue where sometimes the sounds won't stop playing, do you have any reproduction steps so we can take a look at?

**Comment by charliesantos** [comment] 2023-11-30 17:38
@aburkowsky9 this complicates things since there's a task router SDK involved. To better isolate the issue, can you try to reproduce using our Voice JS SDK quickstart https://www.twilio.com/docs/voice/sdks/javascript/get-started?

**Comment by charliesantos** [comment] 2023-11-30 18:32
@aburkowsky9 I understand. The feature is being considered.
Please let me know how it goes once you're able to try the quickstart.

**Comment by charliesantos** [comment] 2024-05-13 20:32
Closing this now. We're tracking this feature request internally. Please feel free to follow up if needed.

**Closed by charliesantos** 2024-05-13 20:32 UTC
Labels: enhancement

**Comment by charliesantos** [comment] 2024-12-04 17:40
@jbadson thanks for reaching out. Public methods for sound controls is high up in the priority. Regarding race conditions, do you have exact reproducible steps using the voice sdk alone? It'll help narrow down the issue. If it's only reproducible with task router, I suggest to submit a support ticket so we can involve other teams.

**Comment by jbadson** [comment] 2024-12-04 18:00
@charliesantos Thanks for the quick response.  I have not tried to reproduce it with the voice SDK alone. I will try to set something up, but not sure how soon I'll be able to get to it.  I will open a support ticket though.

It's just a hunch, but since the only people complaining about this seem to be using taskrouter, I suspect it has something to do with latency introduced by taskrouter creating and cancelling reservations or other internal behavior vs directly controlling calls with the voice API.
