### ISSUE TITLE
[BUG] Angular 13 failed to build 

### ISSUE THREAD

**Issue by nileshzala005** [twilio/twilio-voice.js#46] opened 2021-11-19 10:26 UTC
Getting error while compiling with Angular 13.0.2 and TypeScript 4.4.4

Error: node_modules/@twilio/voice-sdk/es5/twilio/preflight/preflight.d.ts:52:38 - error TS2304: Cannot find name 'DOMError'.

52     failedEvent(error: TwilioError | DOMError): void;

**Comment by shawnostler** [comment] 2021-12-06 21:55
We are facing the same issue. Trying to upgrade to Angular 13 and Typescript 4+.

DOMError was removed in Typescript 4.

**Comment by jorroll** [comment] 2021-12-15 00:59
This appears to be a duplicate of #44

**Comment by ryan-rowland** [comment] 2022-01-19 20:58
I will be closing this as a duplicate of #44. Please follow that issue for updates!

**Closed by ryan-rowland** 2022-01-19 20:58 UTC
Labels: bug
