### ISSUE TITLE
[BUG] Package is published with Node v12 support only, results in warning when installing

### ISSUE THREAD

**Issue by thexeos** [twilio/twilio-voice.js#64] opened 2022-01-15 04:48 UTC
Running LTS version of Node, I get this warning when installing:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@twilio/voice-sdk@2.1.0',     
npm WARN EBADENGINE   required: { node: '12' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.3.1' }
npm WARN EBADENGINE }
```

This is because `package.json` declares support of just the Node v12:

https://github.com/twilio/twilio-voice.js/blob/c1f12bf5889dfdcb1a6ec03ec2488e321efdf2a8/package.json#L15-L17

That needs to be set to `>=12`, or similar.

**Comment by vekerdyb** [comment] 2022-01-17 13:45
This is a duplicate of https://github.com/twilio/twilio-voice.js/issues/60

**Comment by ryan-rowland** [comment] 2022-01-19 20:37
I will be closing this as a duplicate, but know that we have an internal ticket for this and I aim to start processing it this week.

**Closed by ryan-rowland** 2022-01-19 20:37 UTC
Labels: bug
