### ISSUE TITLE
[BUG] TypeError:  Cannot read properties of null (reading 'getSDP') 

### ISSUE THREAD

**Issue by wjlroe** [twilio/twilio-voice.js#98] opened 2022-07-11 16:38 UTC
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Not raising exceptions due to calling `getSDP` on a `null` value.

**Actual behavior:**

Periodically, we get this exception raised by the voice-sdk:

    TypeError: Cannot read properties of null (reading 'getSDP')

Console logs immediately preceding the exception:

```
Setting token and publishing listen
Received connected from pstream
```

We get between 1 and 8 occurences of this error every workday, from a user base
of ~400 users.

Here is the backtrace:

```
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/call.js:250:in getSDP
webpack://[name]/./node_modules/events/events.js:158:in ReflectApply
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/pstream.js:179:in emit
webpack://[name]/./node_modules/events/events.js:153:in ReflectApply
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/wstransport.js:173:in emit
```

**Software versions:**

 - Browser(s): Chrome
 - Operating System: ChromeOS
 - twilio.js: 2.1.1
 - Third-party libraries (e.g., Angular, React, etc.): ReactJS 17.0.39

**Comment by djeer** [comment] 2022-08-03 14:00
duplicates https://github.com/twilio/twilio-voice.js/issues/100

**Comment by djeer** [comment] 2022-08-03 14:01
I'm not the topic-starter, yet...
We're having huge spike of such errors in the last two days.

- Our customers reported call interruptions, that's why we started investigation
- We run E2E tests in CI pipelines and three "headless chrome" events on the screenshot caused exactly three calls test pipeline failures at 15:06 02 Aug 2022 UTC and 11:51, 11:58 03 Aug 2022 UTC
- There are no errors in the Twilio console logs
- There are no active incidents related to calls

![image](https://user-images.githubusercontent.com/3585469/182627498-e441b487-0c17-44b6-aa79-0371d583f350.png)

**Comment by djeer** [comment] 2022-08-03 14:02
duplicated in https://github.com/twilio/twilio-voice.js/issues/100

**Comment by djeer** [comment] 2022-08-03 14:22
Here is our stack trace if it might help

![image](https://user-images.githubusercontent.com/3585469/182632433-b7f39da1-6591-4f27-853f-df1792282b82.png)

**Comment by charliesantos** [comment] 2023-03-21 22:26
Same root cause as https://github.com/twilio/twilio-voice.js/issues/100. Closing this now and let's use. https://github.com/twilio/twilio-voice.js/issues/100 for tracking.

**Closed by charliesantos** 2023-03-21 22:26 UTC
Labels: bug, groomed
